from typing import List
from pydantic import BaseModel, Field
from app.ai.model_router import generate_strategic_insight
from app.core.agent_config import get_agent_config

class LexicalDNAAnalysis(BaseModel):
    style_archetype: str = Field(..., description="The overarching author archetype (e.g., 'The Visionary', 'The Pragmatist', 'The Challenger').")
    vocabulary_density: float = Field(..., description="A float from 0.0 to 1.0 representing the complexity and density of vocabulary used. 1.0 is highly dense.")
    sentence_variance: str = Field(..., description="Description of the variation in sentence length (e.g., 'High (Complex-Short Hybrid)').")
    emotional_resonance: int = Field(..., description="An integer from 0 to 100 capturing how emotionally engaged or potent the writing style is.")
    top_narratives: List[str] = Field(..., description="The central themes or recurring strategic narratives across the posts, limited to 3.")
    suggested_shifts: List[str] = Field(..., description="2-3 actionable insights on how to improve or shift the stylistic delivery for better algorithm traction.")

def analyze_lexical_dna(posts: List[str]) -> LexicalDNAAnalysis:
    """
    Analyzes an array of recent social media posts and constructs the author's true Lexical DNA Fingerprint.
    """
    
    agent = get_agent_config("lexical_dna")
    
    # Combine posts into a single text corpus to avoid token explosion, but clearly separate them
    corpus = "\n\n--- POST ---\n\n".join(posts)

    user_prompt = (
        f"Analyze this content corpus strictly generated by the same author:\n\n{corpus}\n\n"
        "Extract the precise Lexical DNA Fingerprint according to the required schema."
    )

    return generate_strategic_insight(
        system_instruction=agent.system_prompt,
        prompt=user_prompt,
        model=agent.default_model,
        temperature=agent.temperature,
        response_model=LexicalDNAAnalysis
    )
